### ISSUE TITLE
failed action due to sandpaper branch

### ISSUE THREAD

**Issue by avallecam** [Joskerus/Nuevoformato#7]
@Bisaloo the repo is having a failed action (please, follow the [link to the error message](https://github.com/Joskerus/Nuevoformato/actions/runs/7015070592/job/19083783595))

The error line that I found is in the following line ([reference](https://github.com/Joskerus/Nuevoformato/actions/runs/7015070592/job/19083783595#step:6:2228))

```
- Downloading sandpaper from https://carpentries.r-universe.dev/ ... 	ERROR [curl: (22) The requested URL returned error: 404]
```

The call for that action seems to be from this previous line ([reference](https://github.com/Joskerus/Nuevoformato/actions/runs/7015070592/job/19083783595#step:6:2203))

```
# https://carpentries.r-universe.dev/ -----------------------------------------
  - pegboard        [carpentries/pegboard@HEAD -> 0.7.1]
  - sandpaper       [epiverse-trace/sandpaper@translate-spanish -> 0.14.1]
```

Can this be related to having the fork of sandpaper in the r-universe?

**Comment by Bisaloo** [comment]
As far as I can tell, the workbench packages should not be listed in the [`renv.lock` lockfile](https://github.com/Joskerus/Nuevoformato/blob/main/renv/profiles/lesson-requirements/renv.lock). Could you try to remove them?
